### ISSUE TITLE
Ore process loss

### ISSUE THREAD

**Issue by oacaptain** [47MarkIV/Absolute-Ender#6]
After automating the raw ore processing mechanism I observed that ores are lost in the process. The way it works after mining is: a) dump all ores in the simple storage, b) cable takes the ores with exporter to a chest, c) sag mill, d) back in the system through an importer from the sag mill directly, e) export again to a chest, f) alloy smelter, g) back in the system as ingots.
The ores are lost in the first step, during the extraction from the system, and it is consistent, two stacks arrive without any loss the second pair of stacks is 64 and 48 of the respective ore. I think it is a simple storage issue. The exporters and importers have all of them speed and stack upgrades. 
Thank you and I hope my summary makes sense!!!

**Comment by 47MarkIV** [comment]
Thanks for the report, I've been looking into something similar. Can you take out the speed upgrades and see if it's still lost?

**Comment by oacaptain** [comment]
Yes Mark it’s a loss but fewer items this time only 4! 
Did it 4 times only once it lost the 4 items, but the extraction speed from the system isn’t consistent, one time is faster in extracting and other times is slower!

Thank you friend
 George Karpoutzakis from Youtube comments.

Sent from Mail for Windows 10

**Comment by oacaptain** [comment]
And Mark if you increase the extraction speed with speed upgrades the loss gets bigger!

Sent from Mail for Windows 10

**Comment by 47MarkIV** [comment]
Thanks for checking, confirms my suspicion that the upgrades are an issue. I'll file a bug report with the mod author.

**Comment by 47MarkIV** [comment]
Tried updating HammerCore in v1.2, doesn't seem any better. No response from ModDev yet :(

**Comment by oacaptain** [comment]
Thank you Mark for the update, looking forward for a solution!!
Kudos my brother!!

Sent from Mail for Windows 10

**Comment by 47MarkIV** [comment]
Simple storage has updated and this issue was fixed.
